[project]
name = "yt-playlist-download"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pydantic>=2.9.2",
    "pytubefix>=8.4.1",
]
